//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("JONetModel", "FK_INV_DF_INVENTORY_INV_DF_CLARITY", "INV_DIAMONDS_CLARITY", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JON.BackOffice.ImportDiamondCSV.Core.DB.INV_DIAMONDS_CLARITY), "INV_DIAMONDS_INVENTORY", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JON.BackOffice.ImportDiamondCSV.Core.DB.INV_DIAMONDS_INVENTORY), true)]
[assembly: EdmRelationshipAttribute("JONetModel", "FK_INV_DF_INVENTORY_INV_DF_COLOR", "INV_DIAMONDS_COLOR", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JON.BackOffice.ImportDiamondCSV.Core.DB.INV_DIAMONDS_COLOR), "INV_DIAMONDS_INVENTORY", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JON.BackOffice.ImportDiamondCSV.Core.DB.INV_DIAMONDS_INVENTORY), true)]
[assembly: EdmRelationshipAttribute("JONetModel", "FK_INV_DF_INVENTORY_INV_DF_CULET", "INV_DIAMONDS_CULET", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JON.BackOffice.ImportDiamondCSV.Core.DB.INV_DIAMONDS_CULET), "INV_DIAMONDS_INVENTORY", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JON.BackOffice.ImportDiamondCSV.Core.DB.INV_DIAMONDS_INVENTORY), true)]
[assembly: EdmRelationshipAttribute("JONetModel", "FK_INV_DF_INVENTORY_INV_DF_FLUORESCENCE", "INV_DIAMONDS_FLUORESCENCE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JON.BackOffice.ImportDiamondCSV.Core.DB.INV_DIAMONDS_FLUORESCENCE), "INV_DIAMONDS_INVENTORY", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JON.BackOffice.ImportDiamondCSV.Core.DB.INV_DIAMONDS_INVENTORY), true)]
[assembly: EdmRelationshipAttribute("JONetModel", "FK_INV_DF_INVENTORY_INV_DF_REPORT", "INV_DIAMONDS_REPORT", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JON.BackOffice.ImportDiamondCSV.Core.DB.INV_DIAMONDS_REPORT), "INV_DIAMONDS_INVENTORY", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JON.BackOffice.ImportDiamondCSV.Core.DB.INV_DIAMONDS_INVENTORY), true)]
[assembly: EdmRelationshipAttribute("JONetModel", "FK_INV_DF_INVENTORY_INV_DF_SHAPE", "INV_DIAMONDS_SHAPE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JON.BackOffice.ImportDiamondCSV.Core.DB.INV_DIAMONDS_SHAPE), "INV_DIAMONDS_INVENTORY", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JON.BackOffice.ImportDiamondCSV.Core.DB.INV_DIAMONDS_INVENTORY), true)]
[assembly: EdmRelationshipAttribute("JONetModel", "FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING", "INV_DIAMONDS_PROPERTIES_GRADING", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JON.BackOffice.ImportDiamondCSV.Core.DB.INV_DIAMONDS_PROPERTIES_GRADING), "INV_DIAMONDS_INVENTORY", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JON.BackOffice.ImportDiamondCSV.Core.DB.INV_DIAMONDS_INVENTORY), true)]
[assembly: EdmRelationshipAttribute("JONetModel", "FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING1", "INV_DIAMONDS_PROPERTIES_GRADING", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JON.BackOffice.ImportDiamondCSV.Core.DB.INV_DIAMONDS_PROPERTIES_GRADING), "INV_DIAMONDS_INVENTORY", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JON.BackOffice.ImportDiamondCSV.Core.DB.INV_DIAMONDS_INVENTORY), true)]
[assembly: EdmRelationshipAttribute("JONetModel", "FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING2", "INV_DIAMONDS_PROPERTIES_GRADING", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JON.BackOffice.ImportDiamondCSV.Core.DB.INV_DIAMONDS_PROPERTIES_GRADING), "INV_DIAMONDS_INVENTORY", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JON.BackOffice.ImportDiamondCSV.Core.DB.INV_DIAMONDS_INVENTORY), true)]

#endregion

namespace JON.BackOffice.ImportDiamondCSV.Core.DB
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class JONetEntitiesAdmin : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new JONetEntitiesAdmin object using the connection string found in the 'JONetEntitiesAdmin' section of the application configuration file.
        /// </summary>
        public JONetEntitiesAdmin() : base("name=JONetEntitiesAdmin", "JONetEntitiesAdmin")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new JONetEntitiesAdmin object.
        /// </summary>
        public JONetEntitiesAdmin(string connectionString) : base(connectionString, "JONetEntitiesAdmin")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new JONetEntitiesAdmin object.
        /// </summary>
        public JONetEntitiesAdmin(EntityConnection connection) : base(connection, "JONetEntitiesAdmin")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<INV_DIAMONDS_CLARITY> INV_DIAMONDS_CLARITY
        {
            get
            {
                if ((_INV_DIAMONDS_CLARITY == null))
                {
                    _INV_DIAMONDS_CLARITY = base.CreateObjectSet<INV_DIAMONDS_CLARITY>("INV_DIAMONDS_CLARITY");
                }
                return _INV_DIAMONDS_CLARITY;
            }
        }
        private ObjectSet<INV_DIAMONDS_CLARITY> _INV_DIAMONDS_CLARITY;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<INV_DIAMONDS_COLOR> INV_DIAMONDS_COLOR
        {
            get
            {
                if ((_INV_DIAMONDS_COLOR == null))
                {
                    _INV_DIAMONDS_COLOR = base.CreateObjectSet<INV_DIAMONDS_COLOR>("INV_DIAMONDS_COLOR");
                }
                return _INV_DIAMONDS_COLOR;
            }
        }
        private ObjectSet<INV_DIAMONDS_COLOR> _INV_DIAMONDS_COLOR;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<INV_DIAMONDS_CULET> INV_DIAMONDS_CULET
        {
            get
            {
                if ((_INV_DIAMONDS_CULET == null))
                {
                    _INV_DIAMONDS_CULET = base.CreateObjectSet<INV_DIAMONDS_CULET>("INV_DIAMONDS_CULET");
                }
                return _INV_DIAMONDS_CULET;
            }
        }
        private ObjectSet<INV_DIAMONDS_CULET> _INV_DIAMONDS_CULET;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<INV_DIAMONDS_FLUORESCENCE> INV_DIAMONDS_FLUORESCENCE
        {
            get
            {
                if ((_INV_DIAMONDS_FLUORESCENCE == null))
                {
                    _INV_DIAMONDS_FLUORESCENCE = base.CreateObjectSet<INV_DIAMONDS_FLUORESCENCE>("INV_DIAMONDS_FLUORESCENCE");
                }
                return _INV_DIAMONDS_FLUORESCENCE;
            }
        }
        private ObjectSet<INV_DIAMONDS_FLUORESCENCE> _INV_DIAMONDS_FLUORESCENCE;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<INV_DIAMONDS_INVENTORY> INV_DIAMONDS_INVENTORY
        {
            get
            {
                if ((_INV_DIAMONDS_INVENTORY == null))
                {
                    _INV_DIAMONDS_INVENTORY = base.CreateObjectSet<INV_DIAMONDS_INVENTORY>("INV_DIAMONDS_INVENTORY");
                }
                return _INV_DIAMONDS_INVENTORY;
            }
        }
        private ObjectSet<INV_DIAMONDS_INVENTORY> _INV_DIAMONDS_INVENTORY;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<INV_DIAMONDS_PROPERTIES_GRADING> INV_DIAMONDS_PROPERTIES_GRADING
        {
            get
            {
                if ((_INV_DIAMONDS_PROPERTIES_GRADING == null))
                {
                    _INV_DIAMONDS_PROPERTIES_GRADING = base.CreateObjectSet<INV_DIAMONDS_PROPERTIES_GRADING>("INV_DIAMONDS_PROPERTIES_GRADING");
                }
                return _INV_DIAMONDS_PROPERTIES_GRADING;
            }
        }
        private ObjectSet<INV_DIAMONDS_PROPERTIES_GRADING> _INV_DIAMONDS_PROPERTIES_GRADING;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<INV_DIAMONDS_REPORT> INV_DIAMONDS_REPORT
        {
            get
            {
                if ((_INV_DIAMONDS_REPORT == null))
                {
                    _INV_DIAMONDS_REPORT = base.CreateObjectSet<INV_DIAMONDS_REPORT>("INV_DIAMONDS_REPORT");
                }
                return _INV_DIAMONDS_REPORT;
            }
        }
        private ObjectSet<INV_DIAMONDS_REPORT> _INV_DIAMONDS_REPORT;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<INV_DIAMONDS_SHAPE> INV_DIAMONDS_SHAPE
        {
            get
            {
                if ((_INV_DIAMONDS_SHAPE == null))
                {
                    _INV_DIAMONDS_SHAPE = base.CreateObjectSet<INV_DIAMONDS_SHAPE>("INV_DIAMONDS_SHAPE");
                }
                return _INV_DIAMONDS_SHAPE;
            }
        }
        private ObjectSet<INV_DIAMONDS_SHAPE> _INV_DIAMONDS_SHAPE;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the INV_DIAMONDS_CLARITY EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToINV_DIAMONDS_CLARITY(INV_DIAMONDS_CLARITY iNV_DIAMONDS_CLARITY)
        {
            base.AddObject("INV_DIAMONDS_CLARITY", iNV_DIAMONDS_CLARITY);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the INV_DIAMONDS_COLOR EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToINV_DIAMONDS_COLOR(INV_DIAMONDS_COLOR iNV_DIAMONDS_COLOR)
        {
            base.AddObject("INV_DIAMONDS_COLOR", iNV_DIAMONDS_COLOR);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the INV_DIAMONDS_CULET EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToINV_DIAMONDS_CULET(INV_DIAMONDS_CULET iNV_DIAMONDS_CULET)
        {
            base.AddObject("INV_DIAMONDS_CULET", iNV_DIAMONDS_CULET);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the INV_DIAMONDS_FLUORESCENCE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToINV_DIAMONDS_FLUORESCENCE(INV_DIAMONDS_FLUORESCENCE iNV_DIAMONDS_FLUORESCENCE)
        {
            base.AddObject("INV_DIAMONDS_FLUORESCENCE", iNV_DIAMONDS_FLUORESCENCE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the INV_DIAMONDS_INVENTORY EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToINV_DIAMONDS_INVENTORY(INV_DIAMONDS_INVENTORY iNV_DIAMONDS_INVENTORY)
        {
            base.AddObject("INV_DIAMONDS_INVENTORY", iNV_DIAMONDS_INVENTORY);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the INV_DIAMONDS_PROPERTIES_GRADING EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToINV_DIAMONDS_PROPERTIES_GRADING(INV_DIAMONDS_PROPERTIES_GRADING iNV_DIAMONDS_PROPERTIES_GRADING)
        {
            base.AddObject("INV_DIAMONDS_PROPERTIES_GRADING", iNV_DIAMONDS_PROPERTIES_GRADING);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the INV_DIAMONDS_REPORT EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToINV_DIAMONDS_REPORT(INV_DIAMONDS_REPORT iNV_DIAMONDS_REPORT)
        {
            base.AddObject("INV_DIAMONDS_REPORT", iNV_DIAMONDS_REPORT);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the INV_DIAMONDS_SHAPE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToINV_DIAMONDS_SHAPE(INV_DIAMONDS_SHAPE iNV_DIAMONDS_SHAPE)
        {
            base.AddObject("INV_DIAMONDS_SHAPE", iNV_DIAMONDS_SHAPE);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JONetModel", Name="INV_DIAMONDS_CLARITY")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class INV_DIAMONDS_CLARITY : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new INV_DIAMONDS_CLARITY object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="value">Initial value of the value property.</param>
        public static INV_DIAMONDS_CLARITY CreateINV_DIAMONDS_CLARITY(global::System.Int32 id, global::System.String value)
        {
            INV_DIAMONDS_CLARITY iNV_DIAMONDS_CLARITY = new INV_DIAMONDS_CLARITY();
            iNV_DIAMONDS_CLARITY.id = id;
            iNV_DIAMONDS_CLARITY.value = value;
            return iNV_DIAMONDS_CLARITY;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JONetModel", "FK_INV_DF_INVENTORY_INV_DF_CLARITY", "INV_DIAMONDS_INVENTORY")]
        public EntityCollection<INV_DIAMONDS_INVENTORY> INV_DIAMONDS_INVENTORY
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<INV_DIAMONDS_INVENTORY>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_CLARITY", "INV_DIAMONDS_INVENTORY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<INV_DIAMONDS_INVENTORY>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_CLARITY", "INV_DIAMONDS_INVENTORY", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JONetModel", Name="INV_DIAMONDS_COLOR")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class INV_DIAMONDS_COLOR : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new INV_DIAMONDS_COLOR object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="value">Initial value of the value property.</param>
        public static INV_DIAMONDS_COLOR CreateINV_DIAMONDS_COLOR(global::System.Int32 id, global::System.String value)
        {
            INV_DIAMONDS_COLOR iNV_DIAMONDS_COLOR = new INV_DIAMONDS_COLOR();
            iNV_DIAMONDS_COLOR.id = id;
            iNV_DIAMONDS_COLOR.value = value;
            return iNV_DIAMONDS_COLOR;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JONetModel", "FK_INV_DF_INVENTORY_INV_DF_COLOR", "INV_DIAMONDS_INVENTORY")]
        public EntityCollection<INV_DIAMONDS_INVENTORY> INV_DIAMONDS_INVENTORY
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<INV_DIAMONDS_INVENTORY>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_COLOR", "INV_DIAMONDS_INVENTORY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<INV_DIAMONDS_INVENTORY>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_COLOR", "INV_DIAMONDS_INVENTORY", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JONetModel", Name="INV_DIAMONDS_CULET")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class INV_DIAMONDS_CULET : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new INV_DIAMONDS_CULET object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="value">Initial value of the value property.</param>
        public static INV_DIAMONDS_CULET CreateINV_DIAMONDS_CULET(global::System.Int32 id, global::System.String value)
        {
            INV_DIAMONDS_CULET iNV_DIAMONDS_CULET = new INV_DIAMONDS_CULET();
            iNV_DIAMONDS_CULET.id = id;
            iNV_DIAMONDS_CULET.value = value;
            return iNV_DIAMONDS_CULET;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JONetModel", "FK_INV_DF_INVENTORY_INV_DF_CULET", "INV_DIAMONDS_INVENTORY")]
        public EntityCollection<INV_DIAMONDS_INVENTORY> INV_DIAMONDS_INVENTORY
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<INV_DIAMONDS_INVENTORY>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_CULET", "INV_DIAMONDS_INVENTORY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<INV_DIAMONDS_INVENTORY>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_CULET", "INV_DIAMONDS_INVENTORY", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JONetModel", Name="INV_DIAMONDS_FLUORESCENCE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class INV_DIAMONDS_FLUORESCENCE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new INV_DIAMONDS_FLUORESCENCE object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="value">Initial value of the value property.</param>
        public static INV_DIAMONDS_FLUORESCENCE CreateINV_DIAMONDS_FLUORESCENCE(global::System.Int32 id, global::System.String value)
        {
            INV_DIAMONDS_FLUORESCENCE iNV_DIAMONDS_FLUORESCENCE = new INV_DIAMONDS_FLUORESCENCE();
            iNV_DIAMONDS_FLUORESCENCE.id = id;
            iNV_DIAMONDS_FLUORESCENCE.value = value;
            return iNV_DIAMONDS_FLUORESCENCE;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JONetModel", "FK_INV_DF_INVENTORY_INV_DF_FLUORESCENCE", "INV_DIAMONDS_INVENTORY")]
        public EntityCollection<INV_DIAMONDS_INVENTORY> INV_DIAMONDS_INVENTORY
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<INV_DIAMONDS_INVENTORY>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_FLUORESCENCE", "INV_DIAMONDS_INVENTORY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<INV_DIAMONDS_INVENTORY>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_FLUORESCENCE", "INV_DIAMONDS_INVENTORY", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JONetModel", Name="INV_DIAMONDS_INVENTORY")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class INV_DIAMONDS_INVENTORY : EntityObject,IDiamond
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new INV_DIAMONDS_INVENTORY object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="diamondid">Initial value of the diamondid property.</param>
        /// <param name="supplier_code">Initial value of the supplier_code property.</param>
        /// <param name="inventory_code">Initial value of the inventory_code property.</param>
        /// <param name="shape">Initial value of the shape property.</param>
        /// <param name="weight">Initial value of the weight property.</param>
        /// <param name="color">Initial value of the color property.</param>
        /// <param name="clarity">Initial value of the clarity property.</param>
        /// <param name="depth">Initial value of the depth property.</param>
        /// <param name="table">Initial value of the table property.</param>
        /// <param name="fluorescence">Initial value of the fluorescence property.</param>
        /// <param name="length">Initial value of the length property.</param>
        /// <param name="width">Initial value of the width property.</param>
        /// <param name="height">Initial value of the height property.</param>
        /// <param name="symmetrical">Initial value of the symmetrical property.</param>
        /// <param name="polish">Initial value of the polish property.</param>
        /// <param name="grindle">Initial value of the grindle property.</param>
        /// <param name="culet">Initial value of the culet property.</param>
        /// <param name="crown">Initial value of the crown property.</param>
        /// <param name="cut">Initial value of the cut property.</param>
        /// <param name="listprice">Initial value of the listprice property.</param>
        /// <param name="percaratprice">Initial value of the percaratprice property.</param>
        /// <param name="totalprice">Initial value of the totalprice property.</param>
        /// <param name="report">Initial value of the report property.</param>
        /// <param name="reportimg">Initial value of the reportimg property.</param>
        /// <param name="report_number">Initial value of the report_number property.</param>
        public static INV_DIAMONDS_INVENTORY CreateINV_DIAMONDS_INVENTORY(global::System.Int32 id, global::System.Int64 diamondid, global::System.Int32 supplier_code, global::System.String inventory_code, global::System.Int32 shape, global::System.Decimal weight, global::System.Int32 color, global::System.Int32 clarity, global::System.Decimal depth, global::System.Decimal table, global::System.Int32 fluorescence, global::System.Decimal length, global::System.Decimal width, global::System.Decimal height, global::System.Int32 symmetrical, global::System.Int32 polish, global::System.String grindle, global::System.Int32 culet, global::System.Int32 crown, global::System.Int32 cut, global::System.Decimal listprice, global::System.Decimal percaratprice, global::System.Decimal totalprice, global::System.Int32 report, global::System.String reportimg, global::System.String report_number)
        {
            INV_DIAMONDS_INVENTORY iNV_DIAMONDS_INVENTORY = new INV_DIAMONDS_INVENTORY();
            iNV_DIAMONDS_INVENTORY.id = id;
            iNV_DIAMONDS_INVENTORY.diamondid = diamondid;
            iNV_DIAMONDS_INVENTORY.supplier_code = supplier_code;
            iNV_DIAMONDS_INVENTORY.inventory_code = inventory_code;
            iNV_DIAMONDS_INVENTORY.shape = shape;
            iNV_DIAMONDS_INVENTORY.weight = weight;
            iNV_DIAMONDS_INVENTORY.color = color;
            iNV_DIAMONDS_INVENTORY.clarity = clarity;
            iNV_DIAMONDS_INVENTORY.depth = depth;
            iNV_DIAMONDS_INVENTORY.table = table;
            iNV_DIAMONDS_INVENTORY.fluorescence = fluorescence;
            iNV_DIAMONDS_INVENTORY.length = length;
            iNV_DIAMONDS_INVENTORY.width = width;
            iNV_DIAMONDS_INVENTORY.height = height;
            iNV_DIAMONDS_INVENTORY.symmetrical = symmetrical;
            iNV_DIAMONDS_INVENTORY.polish = polish;
            iNV_DIAMONDS_INVENTORY.grindle = grindle;
            iNV_DIAMONDS_INVENTORY.culet = culet;
            iNV_DIAMONDS_INVENTORY.crown = crown;
            iNV_DIAMONDS_INVENTORY.cut = cut;
            iNV_DIAMONDS_INVENTORY.listprice = listprice;
            iNV_DIAMONDS_INVENTORY.percaratprice = percaratprice;
            iNV_DIAMONDS_INVENTORY.totalprice = totalprice;
            iNV_DIAMONDS_INVENTORY.report = report;
            iNV_DIAMONDS_INVENTORY.reportimg = reportimg;
            iNV_DIAMONDS_INVENTORY.report_number = report_number;
            return iNV_DIAMONDS_INVENTORY;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 diamondid
        {
            get
            {
                return _diamondid;
            }
            set
            {
                OndiamondidChanging(value);
                ReportPropertyChanging("diamondid");
                _diamondid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("diamondid");
                OndiamondidChanged();
            }
        }
        private global::System.Int64 _diamondid;
        partial void OndiamondidChanging(global::System.Int64 value);
        partial void OndiamondidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 supplier_code
        {
            get
            {
                return _supplier_code;
            }
            set
            {
                Onsupplier_codeChanging(value);
                ReportPropertyChanging("supplier_code");
                _supplier_code = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("supplier_code");
                Onsupplier_codeChanged();
            }
        }
        private global::System.Int32 _supplier_code;
        partial void Onsupplier_codeChanging(global::System.Int32 value);
        partial void Onsupplier_codeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String inventory_code
        {
            get
            {
                return _inventory_code;
            }
            set
            {
                Oninventory_codeChanging(value);
                ReportPropertyChanging("inventory_code");
                _inventory_code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("inventory_code");
                Oninventory_codeChanged();
            }
        }
        private global::System.String _inventory_code;
        partial void Oninventory_codeChanging(global::System.String value);
        partial void Oninventory_codeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 shape
        {
            get
            {
                return _shape;
            }
            set
            {
                OnshapeChanging(value);
                ReportPropertyChanging("shape");
                _shape = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("shape");
                OnshapeChanged();
            }
        }
        private global::System.Int32 _shape;
        partial void OnshapeChanging(global::System.Int32 value);
        partial void OnshapeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal weight
        {
            get
            {
                return _weight;
            }
            set
            {
                OnweightChanging(value);
                ReportPropertyChanging("weight");
                _weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("weight");
                OnweightChanged();
            }
        }
        private global::System.Decimal _weight;
        partial void OnweightChanging(global::System.Decimal value);
        partial void OnweightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 color
        {
            get
            {
                return _color;
            }
            set
            {
                OncolorChanging(value);
                ReportPropertyChanging("color");
                _color = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("color");
                OncolorChanged();
            }
        }
        private global::System.Int32 _color;
        partial void OncolorChanging(global::System.Int32 value);
        partial void OncolorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 clarity
        {
            get
            {
                return _clarity;
            }
            set
            {
                OnclarityChanging(value);
                ReportPropertyChanging("clarity");
                _clarity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("clarity");
                OnclarityChanged();
            }
        }
        private global::System.Int32 _clarity;
        partial void OnclarityChanging(global::System.Int32 value);
        partial void OnclarityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal depth
        {
            get
            {
                return _depth;
            }
            set
            {
                OndepthChanging(value);
                ReportPropertyChanging("depth");
                _depth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("depth");
                OndepthChanged();
            }
        }
        private global::System.Decimal _depth;
        partial void OndepthChanging(global::System.Decimal value);
        partial void OndepthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal table
        {
            get
            {
                return _table;
            }
            set
            {
                OntableChanging(value);
                ReportPropertyChanging("table");
                _table = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("table");
                OntableChanged();
            }
        }
        private global::System.Decimal _table;
        partial void OntableChanging(global::System.Decimal value);
        partial void OntableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 fluorescence
        {
            get
            {
                return _fluorescence;
            }
            set
            {
                OnfluorescenceChanging(value);
                ReportPropertyChanging("fluorescence");
                _fluorescence = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fluorescence");
                OnfluorescenceChanged();
            }
        }
        private global::System.Int32 _fluorescence;
        partial void OnfluorescenceChanging(global::System.Int32 value);
        partial void OnfluorescenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal length
        {
            get
            {
                return _length;
            }
            set
            {
                OnlengthChanging(value);
                ReportPropertyChanging("length");
                _length = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("length");
                OnlengthChanged();
            }
        }
        private global::System.Decimal _length;
        partial void OnlengthChanging(global::System.Decimal value);
        partial void OnlengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal width
        {
            get
            {
                return _width;
            }
            set
            {
                OnwidthChanging(value);
                ReportPropertyChanging("width");
                _width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("width");
                OnwidthChanged();
            }
        }
        private global::System.Decimal _width;
        partial void OnwidthChanging(global::System.Decimal value);
        partial void OnwidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal height
        {
            get
            {
                return _height;
            }
            set
            {
                OnheightChanging(value);
                ReportPropertyChanging("height");
                _height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("height");
                OnheightChanged();
            }
        }
        private global::System.Decimal _height;
        partial void OnheightChanging(global::System.Decimal value);
        partial void OnheightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 symmetrical
        {
            get
            {
                return _symmetrical;
            }
            set
            {
                OnsymmetricalChanging(value);
                ReportPropertyChanging("symmetrical");
                _symmetrical = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("symmetrical");
                OnsymmetricalChanged();
            }
        }
        private global::System.Int32 _symmetrical;
        partial void OnsymmetricalChanging(global::System.Int32 value);
        partial void OnsymmetricalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 polish
        {
            get
            {
                return _polish;
            }
            set
            {
                OnpolishChanging(value);
                ReportPropertyChanging("polish");
                _polish = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("polish");
                OnpolishChanged();
            }
        }
        private global::System.Int32 _polish;
        partial void OnpolishChanging(global::System.Int32 value);
        partial void OnpolishChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String grindle
        {
            get
            {
                return _grindle;
            }
            set
            {
                OngrindleChanging(value);
                ReportPropertyChanging("grindle");
                _grindle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("grindle");
                OngrindleChanged();
            }
        }
        private global::System.String _grindle;
        partial void OngrindleChanging(global::System.String value);
        partial void OngrindleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 culet
        {
            get
            {
                return _culet;
            }
            set
            {
                OnculetChanging(value);
                ReportPropertyChanging("culet");
                _culet = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("culet");
                OnculetChanged();
            }
        }
        private global::System.Int32 _culet;
        partial void OnculetChanging(global::System.Int32 value);
        partial void OnculetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 crown
        {
            get
            {
                return _crown;
            }
            set
            {
                OncrownChanging(value);
                ReportPropertyChanging("crown");
                _crown = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("crown");
                OncrownChanged();
            }
        }
        private global::System.Int32 _crown;
        partial void OncrownChanging(global::System.Int32 value);
        partial void OncrownChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cut
        {
            get
            {
                return _cut;
            }
            set
            {
                OncutChanging(value);
                ReportPropertyChanging("cut");
                _cut = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cut");
                OncutChanged();
            }
        }
        private global::System.Int32 _cut;
        partial void OncutChanging(global::System.Int32 value);
        partial void OncutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal listprice
        {
            get
            {
                return _listprice;
            }
            set
            {
                OnlistpriceChanging(value);
                ReportPropertyChanging("listprice");
                _listprice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("listprice");
                OnlistpriceChanged();
            }
        }
        private global::System.Decimal _listprice;
        partial void OnlistpriceChanging(global::System.Decimal value);
        partial void OnlistpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal percaratprice
        {
            get
            {
                return _percaratprice;
            }
            set
            {
                OnpercaratpriceChanging(value);
                ReportPropertyChanging("percaratprice");
                _percaratprice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("percaratprice");
                OnpercaratpriceChanged();
            }
        }
        private global::System.Decimal _percaratprice;
        partial void OnpercaratpriceChanging(global::System.Decimal value);
        partial void OnpercaratpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal totalprice
        {
            get
            {
                return _totalprice;
            }
            set
            {
                OntotalpriceChanging(value);
                ReportPropertyChanging("totalprice");
                _totalprice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totalprice");
                OntotalpriceChanged();
            }
        }
        private global::System.Decimal _totalprice;
        partial void OntotalpriceChanging(global::System.Decimal value);
        partial void OntotalpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 report
        {
            get
            {
                return _report;
            }
            set
            {
                OnreportChanging(value);
                ReportPropertyChanging("report");
                _report = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("report");
                OnreportChanged();
            }
        }
        private global::System.Int32 _report;
        partial void OnreportChanging(global::System.Int32 value);
        partial void OnreportChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String reportimg
        {
            get
            {
                return _reportimg;
            }
            set
            {
                OnreportimgChanging(value);
                ReportPropertyChanging("reportimg");
                _reportimg = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("reportimg");
                OnreportimgChanged();
            }
        }
        private global::System.String _reportimg;
        partial void OnreportimgChanging(global::System.String value);
        partial void OnreportimgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String report_number
        {
            get
            {
                return _report_number;
            }
            set
            {
                Onreport_numberChanging(value);
                ReportPropertyChanging("report_number");
                _report_number = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("report_number");
                Onreport_numberChanged();
            }
        }
        private global::System.String _report_number;
        partial void Onreport_numberChanging(global::System.String value);
        partial void Onreport_numberChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JONetModel", "FK_INV_DF_INVENTORY_INV_DF_CLARITY", "INV_DIAMONDS_CLARITY")]
        public INV_DIAMONDS_CLARITY INV_DIAMONDS_CLARITY
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_CLARITY>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_CLARITY", "INV_DIAMONDS_CLARITY").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_CLARITY>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_CLARITY", "INV_DIAMONDS_CLARITY").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<INV_DIAMONDS_CLARITY> INV_DIAMONDS_CLARITYReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_CLARITY>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_CLARITY", "INV_DIAMONDS_CLARITY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<INV_DIAMONDS_CLARITY>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_CLARITY", "INV_DIAMONDS_CLARITY", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JONetModel", "FK_INV_DF_INVENTORY_INV_DF_COLOR", "INV_DIAMONDS_COLOR")]
        public INV_DIAMONDS_COLOR INV_DIAMONDS_COLOR
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_COLOR>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_COLOR", "INV_DIAMONDS_COLOR").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_COLOR>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_COLOR", "INV_DIAMONDS_COLOR").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<INV_DIAMONDS_COLOR> INV_DIAMONDS_COLORReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_COLOR>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_COLOR", "INV_DIAMONDS_COLOR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<INV_DIAMONDS_COLOR>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_COLOR", "INV_DIAMONDS_COLOR", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JONetModel", "FK_INV_DF_INVENTORY_INV_DF_CULET", "INV_DIAMONDS_CULET")]
        public INV_DIAMONDS_CULET INV_DIAMONDS_CULET
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_CULET>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_CULET", "INV_DIAMONDS_CULET").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_CULET>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_CULET", "INV_DIAMONDS_CULET").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<INV_DIAMONDS_CULET> INV_DIAMONDS_CULETReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_CULET>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_CULET", "INV_DIAMONDS_CULET");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<INV_DIAMONDS_CULET>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_CULET", "INV_DIAMONDS_CULET", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JONetModel", "FK_INV_DF_INVENTORY_INV_DF_FLUORESCENCE", "INV_DIAMONDS_FLUORESCENCE")]
        public INV_DIAMONDS_FLUORESCENCE INV_DIAMONDS_FLUORESCENCE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_FLUORESCENCE>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_FLUORESCENCE", "INV_DIAMONDS_FLUORESCENCE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_FLUORESCENCE>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_FLUORESCENCE", "INV_DIAMONDS_FLUORESCENCE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<INV_DIAMONDS_FLUORESCENCE> INV_DIAMONDS_FLUORESCENCEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_FLUORESCENCE>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_FLUORESCENCE", "INV_DIAMONDS_FLUORESCENCE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<INV_DIAMONDS_FLUORESCENCE>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_FLUORESCENCE", "INV_DIAMONDS_FLUORESCENCE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JONetModel", "FK_INV_DF_INVENTORY_INV_DF_REPORT", "INV_DIAMONDS_REPORT")]
        public INV_DIAMONDS_REPORT INV_DIAMONDS_REPORT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_REPORT>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_REPORT", "INV_DIAMONDS_REPORT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_REPORT>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_REPORT", "INV_DIAMONDS_REPORT").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<INV_DIAMONDS_REPORT> INV_DIAMONDS_REPORTReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_REPORT>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_REPORT", "INV_DIAMONDS_REPORT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<INV_DIAMONDS_REPORT>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_REPORT", "INV_DIAMONDS_REPORT", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JONetModel", "FK_INV_DF_INVENTORY_INV_DF_SHAPE", "INV_DIAMONDS_SHAPE")]
        public INV_DIAMONDS_SHAPE INV_DIAMONDS_SHAPE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_SHAPE>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_SHAPE", "INV_DIAMONDS_SHAPE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_SHAPE>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_SHAPE", "INV_DIAMONDS_SHAPE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<INV_DIAMONDS_SHAPE> INV_DIAMONDS_SHAPEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_SHAPE>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_SHAPE", "INV_DIAMONDS_SHAPE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<INV_DIAMONDS_SHAPE>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_SHAPE", "INV_DIAMONDS_SHAPE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JONetModel", "FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING", "INV_DIAMONDS_PROPERTIES_GRADING")]
        public INV_DIAMONDS_PROPERTIES_GRADING INV_DIAMONDS_PROPERTIES_GRADING
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_PROPERTIES_GRADING>("JONetModel.FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING", "INV_DIAMONDS_PROPERTIES_GRADING").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_PROPERTIES_GRADING>("JONetModel.FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING", "INV_DIAMONDS_PROPERTIES_GRADING").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<INV_DIAMONDS_PROPERTIES_GRADING> INV_DIAMONDS_PROPERTIES_GRADINGReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_PROPERTIES_GRADING>("JONetModel.FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING", "INV_DIAMONDS_PROPERTIES_GRADING");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<INV_DIAMONDS_PROPERTIES_GRADING>("JONetModel.FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING", "INV_DIAMONDS_PROPERTIES_GRADING", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JONetModel", "FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING1", "INV_DIAMONDS_PROPERTIES_GRADING")]
        public INV_DIAMONDS_PROPERTIES_GRADING INV_DIAMONDS_PROPERTIES_GRADING1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_PROPERTIES_GRADING>("JONetModel.FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING1", "INV_DIAMONDS_PROPERTIES_GRADING").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_PROPERTIES_GRADING>("JONetModel.FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING1", "INV_DIAMONDS_PROPERTIES_GRADING").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<INV_DIAMONDS_PROPERTIES_GRADING> INV_DIAMONDS_PROPERTIES_GRADING1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_PROPERTIES_GRADING>("JONetModel.FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING1", "INV_DIAMONDS_PROPERTIES_GRADING");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<INV_DIAMONDS_PROPERTIES_GRADING>("JONetModel.FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING1", "INV_DIAMONDS_PROPERTIES_GRADING", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JONetModel", "FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING2", "INV_DIAMONDS_PROPERTIES_GRADING")]
        public INV_DIAMONDS_PROPERTIES_GRADING INV_DIAMONDS_PROPERTIES_GRADING2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_PROPERTIES_GRADING>("JONetModel.FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING2", "INV_DIAMONDS_PROPERTIES_GRADING").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_PROPERTIES_GRADING>("JONetModel.FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING2", "INV_DIAMONDS_PROPERTIES_GRADING").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<INV_DIAMONDS_PROPERTIES_GRADING> INV_DIAMONDS_PROPERTIES_GRADING2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INV_DIAMONDS_PROPERTIES_GRADING>("JONetModel.FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING2", "INV_DIAMONDS_PROPERTIES_GRADING");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<INV_DIAMONDS_PROPERTIES_GRADING>("JONetModel.FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING2", "INV_DIAMONDS_PROPERTIES_GRADING", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JONetModel", Name="INV_DIAMONDS_PROPERTIES_GRADING")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class INV_DIAMONDS_PROPERTIES_GRADING : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new INV_DIAMONDS_PROPERTIES_GRADING object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="value">Initial value of the value property.</param>
        public static INV_DIAMONDS_PROPERTIES_GRADING CreateINV_DIAMONDS_PROPERTIES_GRADING(global::System.Int32 id, global::System.String value)
        {
            INV_DIAMONDS_PROPERTIES_GRADING iNV_DIAMONDS_PROPERTIES_GRADING = new INV_DIAMONDS_PROPERTIES_GRADING();
            iNV_DIAMONDS_PROPERTIES_GRADING.id = id;
            iNV_DIAMONDS_PROPERTIES_GRADING.value = value;
            return iNV_DIAMONDS_PROPERTIES_GRADING;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JONetModel", "FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING", "INV_DIAMONDS_INVENTORY")]
        public EntityCollection<INV_DIAMONDS_INVENTORY> INV_DIAMONDS_INVENTORY
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<INV_DIAMONDS_INVENTORY>("JONetModel.FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING", "INV_DIAMONDS_INVENTORY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<INV_DIAMONDS_INVENTORY>("JONetModel.FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING", "INV_DIAMONDS_INVENTORY", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JONetModel", "FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING1", "INV_DIAMONDS_INVENTORY")]
        public EntityCollection<INV_DIAMONDS_INVENTORY> INV_DIAMONDS_INVENTORY1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<INV_DIAMONDS_INVENTORY>("JONetModel.FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING1", "INV_DIAMONDS_INVENTORY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<INV_DIAMONDS_INVENTORY>("JONetModel.FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING1", "INV_DIAMONDS_INVENTORY", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JONetModel", "FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING2", "INV_DIAMONDS_INVENTORY")]
        public EntityCollection<INV_DIAMONDS_INVENTORY> INV_DIAMONDS_INVENTORY2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<INV_DIAMONDS_INVENTORY>("JONetModel.FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING2", "INV_DIAMONDS_INVENTORY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<INV_DIAMONDS_INVENTORY>("JONetModel.FK_INV_DIAMONDS_INVENTORY_INV_DIAMONDS_PROPERTIES_GRADING2", "INV_DIAMONDS_INVENTORY", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JONetModel", Name="INV_DIAMONDS_REPORT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class INV_DIAMONDS_REPORT : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new INV_DIAMONDS_REPORT object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="value">Initial value of the value property.</param>
        public static INV_DIAMONDS_REPORT CreateINV_DIAMONDS_REPORT(global::System.Int32 id, global::System.String value)
        {
            INV_DIAMONDS_REPORT iNV_DIAMONDS_REPORT = new INV_DIAMONDS_REPORT();
            iNV_DIAMONDS_REPORT.id = id;
            iNV_DIAMONDS_REPORT.value = value;
            return iNV_DIAMONDS_REPORT;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JONetModel", "FK_INV_DF_INVENTORY_INV_DF_REPORT", "INV_DIAMONDS_INVENTORY")]
        public EntityCollection<INV_DIAMONDS_INVENTORY> INV_DIAMONDS_INVENTORY
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<INV_DIAMONDS_INVENTORY>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_REPORT", "INV_DIAMONDS_INVENTORY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<INV_DIAMONDS_INVENTORY>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_REPORT", "INV_DIAMONDS_INVENTORY", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JONetModel", Name="INV_DIAMONDS_SHAPE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class INV_DIAMONDS_SHAPE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new INV_DIAMONDS_SHAPE object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="value">Initial value of the value property.</param>
        public static INV_DIAMONDS_SHAPE CreateINV_DIAMONDS_SHAPE(global::System.Int32 id, global::System.String value)
        {
            INV_DIAMONDS_SHAPE iNV_DIAMONDS_SHAPE = new INV_DIAMONDS_SHAPE();
            iNV_DIAMONDS_SHAPE.id = id;
            iNV_DIAMONDS_SHAPE.value = value;
            return iNV_DIAMONDS_SHAPE;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JONetModel", "FK_INV_DF_INVENTORY_INV_DF_SHAPE", "INV_DIAMONDS_INVENTORY")]
        public EntityCollection<INV_DIAMONDS_INVENTORY> INV_DIAMONDS_INVENTORY
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<INV_DIAMONDS_INVENTORY>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_SHAPE", "INV_DIAMONDS_INVENTORY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<INV_DIAMONDS_INVENTORY>("JONetModel.FK_INV_DF_INVENTORY_INV_DF_SHAPE", "INV_DIAMONDS_INVENTORY", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
